### ISSUE TITLE
No documentation available how to use

### ISSUE THREAD

**Issue by gruijter** [Coximus/NodePlugwise#15]
Great work!

Where can I find more information on typical use cases?

e.g:
- How to set it up
- how to get circle status (on/off state, power measuring)
- how to set the circle state (on/off)
- how to set time schedules etc.
- ......

**Comment by Coximus** [comment]
Thanks. This is VERY much a work in progress at the moment, but I am actively working on it. Today I will be creating a npm package and some sample code to get started.

At the moment it is only capable of switching circle plugs on/off, but I have figured out most of the other functionality, I just need to implement them.

I won't close this comment yet, I'll reply when I have an npm package working, hopefully later today

**Comment by Coximus** [comment]
I've updated the README with some example usage, and I have created a VERY basic web interface here https://github.com/Coximus/NodePlugwiseAPI which is hardcoded to my serial port and a single plug at the moment, but I will be building upon that interface for my own purposes. Keep an eye on them and hopefully you will find them useful too.
